version: "3.8"

services:
  avatars:
    image: avatarsf
    container_name: avatars
    ports:
      - "5000:5000"

  avatar-frontend:
    image: avatar-frontend1
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
