version: "3.8"

services:
  avatars:
    image: avatarsf
    container_name: avatars
    ports:
      - "5000:5000"

  avatar-frontend:
    image: avatar-frontend3
    environment:
      - VITE_HOST=${VITE_HOST}
      - VITE_PORT=${VITE_PORT}
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
